### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/Renewal-Design-Html#85]
Hi @AnKar112 ... Nice to see you. Hope you are well!

Your updates to the main page look great. Just two requests...

1. I'm sure you noticed in the Figma design there is one row with the Return page icon in it. I'm sure you've allowed for that in the code, but can you please demonstrate one row for us? (See screenshot below.) In the In-Service list, a row will have EITHER the Return icon, or BOTH the Give AND Take icons. The Waiting list will be as it was before, no Return, Give or Take icons. But it's fine that you've turned them on here. The Finished list will only have the Give and Take icons.
![return-icon](https://user-images.githubusercontent.com/13606352/191875248-64fa2718-87b6-4da9-967f-7c743c591c73.png)

2. I'd like the Return, Give and Take icons to have color by default without hover. These are actually links that will immediately take users to the relevant pages, for me, no hover or click/tap actions are necessary. Do you agree with this? However, the food button is perfect as it is. Do not change it.

**Comment by AnKar112** [comment]
1 - done, you can check the first row
2 - as you wish. as for me, now they look nice. But we can remove the active state, it's really unnecessary. Changing how these buttons work will take ~two minutes.

**Comment by d33pspace** [comment]
@AnKar112 
1 - Looks great. Thank you!
2 - Thanks for the information. Let's please go with Return, Take and Give buttons all with their respective colors by default and no changes for hover or action. So when the page opens, these buttons should have colors. The Food button and Shower icons are perfect as they are. Do not change them.

**Comment by AnKar112** [comment]
Done

**Comment by d33pspace** [comment]
Hi @AnKar112 ... The Return, Take and Give buttons look great! But somehow the Food button (bowl of rice with chopsticks) is broken now. I liked it exactly how it was before - can you change that one back? 😊

**Comment by AnKar112** [comment]
If I get you right, you want that The Return, Take, and Give buttons always have a state with colors, the shower icon always has grey color, and the food icon be with an active\hover state. Am I right? Check it now

**Comment by d33pspace** [comment]
This is perfect, @AnKar112 ... thank you!
